name: Bun

on:
  push:
    branches:
      - main # Execute on every push
  workflow_dispatch: # Execute on manual trigger
jobs:
  publish-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun ./index.ts
      #- run: bun run build
